### ISSUE TITLE
[Bug]: build fails on CI run with missing module 'rollup'

### ISSUE THREAD

**Issue by homj** [ng-packagr/ng-packagr#2749]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

With the recent release of 17.0.2, my Github Actions workflow fails with the error 
```
Cannot find module 'rollup'
```

This is probably a regression introduced by https://github.com/ng-packagr/ng-packagr/pull/2725

I'm using Nx workspace. Then workspace contains one app and one library.

#### How To Reproduce
1. Create a nx workspace containing an angular application
2. add a publishable angular library
3. add a GH workflow that runs `npm ci` & `npx nx affected:build`
4. The build command will fail when trying to build the library. Both commands succeed when run locally

#### Expected Behaviour

The build command should not fail when run inside a GH workflow

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            17.0.2
@angular/compiler:     17.0.7
rollup:                4.9.0
typescript:            5.2.2
```

other versions:

```
nx: 17.2.5
```

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.7
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@angular/cdk                    17.0.4
@schematics/angular             17.0.7
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

```
