### ISSUE TITLE
JSON import not copied into lib with .d.ts files, cannot build app that imports the lib

### ISSUE THREAD

**Issue by henrahmagix** [ng-packagr/ng-packagr#1496]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Since #1050, we can import JSON files and they are correctly bundled into a library build. I love this! It allows me to define contracts through JSON and use that as both a value and a type with `typeof`.

However, when importing that library into an app, Typescript complains that the JSON file cannot be found: it is referenced from a .d.ts file, but was not copied into the .d.ts folder tree.

#### How To Reproduce

First generate a library:
```bash
$ ng new json-bug --create-application=false
$ cd json-bug
$ ng generate library json-bug
```

Then create some JSON and use it as both a value and a type:
```diff
diff --git a/projects/json-bug/src/lib/config.json b/projects/json-bug/src/lib/config.json
new file mode 100644
index 0000000..d6630bc
--- /dev/null
+++ b/projects/json-bug/src/lib/config.json
@@ -0,0 +1,3 @@
+{
+  "base": "http://example.org"
+}
diff --git a/projects/json-bug/src/lib/json-bug.service.ts b/projects/json-bug/src/lib/json-bug.service.ts
index 59a557b..68c3096 100644
--- a/projects/json-bug/src/lib/json-bug.service.ts
+++ b/projects/json-bug/src/lib/json-bug.service.ts
@@ -1,9 +1,24 @@
 import { Injectable } from '@angular/core';
+import defaultConfig from './config.json';
+
+type ConfigJSON = typeof defaultConfig;
+
+@Injectable()
+export class Config implements ConfigJSON {
+  base: string;
+}
 
 @Injectable({
   providedIn: 'root'
 })
 export class JsonBugService {
+  private API: string;
 
-  constructor() { }
+  constructor(config: Config) {
+    this.API = config.base;
+  }
 }
```

Follow instructions to allow JSON files from https://github.com/ng-packagr/ng-packagr/commit/1bf8eaf589b41208000c459deb613bdb40e2cb6b:
```diff
diff --git a/projects/json-bug/tsconfig.lib.json b/projects/json-bug/tsconfig.lib.json
index bd23948..61e9a08 100644
--- a/projects/json-bug/tsconfig.lib.json
+++ b/projects/json-bug/tsconfig.lib.json
@@ -12,7 +12,7 @@
     ]
   },
   "angularCompilerOptions": {
-    "annotateForClosureCompiler": true,
+    "annotateForClosureCompiler": false,
     "skipTemplateCodegen": true,
     "strictMetadataEmit": true,
     "fullTemplateTypeCheck": true,
diff --git a/tsconfig.json b/tsconfig.json
index 9307256..ffd1cef 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -10,6 +10,9 @@
     "module": "esnext",
     "moduleResolution": "node",
     "importHelpers": true,
+    "resolveJsonModule": true,
+    "esModuleInterop": true,
+    "allowSyntheticDefaultImports": true,
     "target": "es2015",
     "typeRoots": [
       "node_modules/@types"
```

Build the library and inspect the dist:
```bash
$ ng build
$ head -1 dist/json-bug/lib/json-bug.service.d.ts
import defaultConfig from './config.json';
$ tree dist/json-bug/lib
dist/json-bug/lib
├── json-bug.component.d.ts
├── json-bug.module.d.ts
└── json-bug.service.d.ts
```

There's no `config.json` file in `lib`, so the import in `json-bug.service.d.ts` fails when using in an app.

Generate an app to test the import:
```bash
$ ng generate app testing --style css --routing false
```

Import the library:
```diff
diff --git a/projects/testing/src/app/app.module.ts b/projects/testing/src/app/app.module.ts
index f657163..5c9a398 100644
--- a/projects/testing/src/app/app.module.ts
+++ b/projects/testing/src/app/app.module.ts
@@ -2,6 +2,7 @@ import { BrowserModule } from '@angular/platform-browser';
 import { NgModule } from '@angular/core';
 
 import { AppComponent } from './app.component';
+import { Config } from 'json-bug';
 
 @NgModule({
   declarations: [
@@ -10,7 +11,9 @@ import { AppComponent } from './app.component';
   imports: [
     BrowserModule
   ],
-  providers: [],
+  providers: [
+    {provide: Config, useValue: {base: 'https://new-base.org'}},
+  ],
   bootstrap: [AppComponent]
 })
 export class AppModule { }
```

Build the testing app:
```bash
$ ng build testing

ERROR in ../../dist/json-bug/lib/json-bug.service.d.ts:1:27 - error TS2307: Cannot find module './config.json'.

1 import defaultConfig from './config.json';
                            ~~~~~~~~~~~~~~~
```

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

Failing test in #1505

#### Expected Behaviour

The JSON file is available in the dist for the .d.ts files, _or_ it is inlined into the .d.ts files.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.7.1
@angular/compiler:     8.2.14
rollup:                1.25.2
tsickle:               0.37.1
typescript:            3.5.3
$ node --version
v12.4.0
$ npm --version
6.13.4
```

RxJS is at 6.4.0, but I don't think that's relevant.

**Comment by henrahmagix** [comment]
@alan-agius4 Please see #1505 =)

**Comment by alan-agius4** [comment]
I had a look at this and it appears that the TypeScript compiler is emitted the wrong path to the JSON file in the DTS file. when the `declarationDir` differs from `outDir`.

```json
{
  "compilerOptions": {
    "declarationDir": "../../out-tsc",
    "outDir": "../../out-tsc/lib",
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "resolveJsonModule": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ]
  }
}
```

The generated DTS file will refer the json file as follows, however the JSON file is located in `./lib/example.json`.
```ts
export { default as numbers } from './example.json';
```

I'm sorry, but this issue is not caused by ng-packagr. Please contact the author(s) of the TypeScript project or file an issue on their issue tracker.
