### ISSUE TITLE
Exporting modules from outside the library folder fails with an error

### ISSUE THREAD

**Issue by sinedied** [ng-packagr/ng-packagr#358]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

I'm trying to export parts of an existing angular app as a library, but it seems there is path issues.
Here is my folder structure:
![image](https://user-images.githubusercontent.com/593151/33556861-a8bad4aa-d905-11e7-8d9b-0a039b9db0cd.png)

And my `public_api.ts`:
```ts
export * from '../src/app/shared/shared.module';
```
But when trying to build the library, I get this error:
```
Building Angular library from lib/ng-package.json

BUILD ERROR
Error at /Users/noda/github/addon-library/test/lib/.ng_build/ts/public_api.ts:2:15: Cannot find module '../src/app/shared/shared.module'.
Error: Error at /Users/noda/github/addon-library/test/lib/.ng_build/ts/public_api.ts:2:15: Cannot find module '../src/app/shared/shared.module'.
    at new UserError (/Users/noda/github/addon-library/test/node_modules/@angular/tsc-wrapped/src/tsc.js:27:28)
    at check (/Users/noda/github/addon-library/test/node_modules/@angular/tsc-wrapped/src/tsc.js:93:15)
    at Tsc.typeCheck (/Users/noda/github/addon-library/test/node_modules/@angular/tsc-wrapped/src/tsc.js:173:9)
    at /Users/noda/github/addon-library/test/node_modules/@angular/tsc-wrapped/src/main.js:122:23
    at <anonymous>
```

#### How To Reproduce

1. Create a typical `angular-cli` app with a feature module.
2. Create a dedicated `lib` folder containing `ng-packagr` configuration
3. Try to export your app feature module in `lib/public_api.ts` with something like `export * from '../src/app/my-feature/my-feature.module';`
4. Build the library

#### Expected Behaviour

The library builds without error 😄 

#### Version Information

```
ng-packagr: v1.6.0
node: v8.8.1
@angular: v5.0.5
rxjs: 5.5.2
zone.js: 0.8.14
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by willgm** [comment]
I'm facing the same problem, because I have some internal shared code used for some different libs.

**Comment by sinedied** [comment]
Any news on this?

**Comment by dherges** [comment]
Hi all,

you can see it as a bug or as a missing feature, if you like to. I'd recommend to organise the source files as [demo'ed in the nx-packaged repo](https://github.com/dherges/nx-packaged) and have a `package.json` per each library in the `libs` folder and extract shared code from an app's code base to a dedicated library folder.

**Comment by dherges** [comment]
If that's not what you're intending after all, I'd recommend to move the `package.json` to the sub-folder inside `src/app/<feature>`.

**Comment by dherges** [comment]
On another question, does that only happen in v1? Does it work with v2 (current 2.0.0-rc.13 or `ng-packagr@next`)?

**Comment by sinedied** [comment]
@dherges I'll test this an report ASAP

**Comment by sinedied** [comment]
Just tried, the error changed:
```
BUILD ERROR
error TS6059: File '/Users/noda/github/addon-library/test/src/app/material.module.ts' is not under 'rootDir' '/Users/noda/github/addon-library/test/lib'. 'rootDir' is expected to contain all source files.
e
...
```
Is there any way to configure `rootDir` in `ng-packagr.json`?

**Comment by dherges** [comment]
You could do the with the programmtic API, see #517

**Comment by sabbirrahman** [comment]
I'm facing same kind of problem. I tried using the programatic API. Here is my tsconfig-custom.json.
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "rootDir": "src/",
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
But still got `'rootDir' is expected to contain all source files.`

**Comment by mariohmol** [comment]
Hi there.. having something similar , any ideas?

https://github.com/mariohmol/ang-jsoneditor/issues/3

**Comment by elesueur** [comment]
I'm also trying to include common code in a number of shared libraries and getting the file outside rootDir issue.

Being able to programmatically compile and override rootDir in a custom tsconfig is not helping, because ng-packagr just overwrites the rootDir I specified in https://github.com/dherges/ng-packagr/blob/master/src/lib/ts/tsconfig.ts#L55

Seems like there is currently no way to include common code in a number of libraries.

**Comment by cseale** [comment]
Also facing a similar issue here.

**Comment by mariohmol** [comment]
Could make it work.. dont remembr exactly what i did.. but here is the discussion and some commit where u can follow https://github.com/mariohmol/ang-jsoneditor/issues/3

**Comment by sinedied** [comment]
@dherges any ideas about this one?

What I would like to achieve is to export some parts of a standard angular project as a library without altering the original structure, so moving down the `package.json` file is not an option here.

I also tried the programmatic API, still no luck.

**Comment by annalen** [comment]
I get the same error when using sencondary entry points.

I try to build the library according to the following scheme:
- All services which have to have one and only one instance per application should be implemented in the BarModule here.
- And ViewModules should import services from FooModule.

Here is a link to the git project of the sample library: 
https://github.com/annalen/example-library.

This example project is structured as follows:
```
example-library
├── foo
|   ├── bar
|   |	├── src
|   |	|   ├── bar.module.ts
|   |	|   └── settings.service.ts
|   |	├── index.ts
|   |	├── package.json
|   |	└── public_api.ts
|   ├── view
|   |	├── src
|   |	|   ├── view.component.ts
|   |	|   ├── view.component.html
|   |	|   └── view.module.ts
|   |	├── index.ts
|   |	├── package.json
|   |	└── public_api.ts
|   └── package.json
├── public_api.ts
└── package.json
```



In this example case, the ViewModule imports the BarModule and the ViewComponent uses the SettingsService.

And I think that's why I get the following error.:

```
File '.../example-library/lib/foo/bar/src/bar.module.ts' is not under 'rootDir' 
'...\example-library\lib\foo\view'. 'rootDir' is expected to contain all source files.
error TS6059: 
File '.../example-library/lib/foo/bar/src/settings.service.ts' is not under 'rootDir' 
'..\example-library\lib\foo\view'. 'rootDir' is expected to contain all source files.
```


Thank you for your help.

**Comment by deanpeterson** [comment]
Getting the same error. This makes ng-packagr worthless.

**Comment by marioteik** [comment]
+1

**Comment by samdelagarza** [comment]
+1

**Comment by joshuaball** [comment]
+1

**Comment by choucry13** [comment]
+1

**Comment by Pringels** [comment]
+1

**Comment by sinedied** [comment]
@dherges Could you explain why this was tagged as wontfix?

**Comment by TempleOfTemplar** [comment]
+1

**Comment by allenhwkim** [comment]
I have found this solution from https://github.com/dherges/nx-packaged
package.json
```
  "scripts": {
    "build:libs": "yarn libs:one-lib:build && yarn libs:two-lib:build && yarn libs:three-lib:build",
    "libs:one-lib:build": "ng-packagr -p libs/one-lib/package.json ",
    "libs:two-lib:build": "ng-packagr -p libs/two-lib/package.json",
    "libs:three-lib:build": "ts-node libs/three-lib/build.ts"
  }
```
```
$ npm run build:libs
```
output
```
nx-packaged$ (master) tree \@nx-packaged/
@nx-packaged/
├── one-lib
│   ├── bundles
│   ├── esm2015
│   ├── esm5
│   ├── index.d.ts
│   ├── nx-packaged-one-lib.d.ts
│   ├── nx-packaged-one-lib.metadata.json
│   ├── package.json
│   └── src
│       └── one-lib.d.ts
├── one-lib.tgz
├── three-lib
│   ├── bundles
│   ├── esm2015p
│   ├── esm5
│   ├── index.metadata.json
│   ├── nx-packaged-three-lib.metadata.json
│   ├── package.json
│   └── src
│       ├── es2017
│       └── three-lib.module.metadata.json
├── three-lib.tgz
├── two-lib
│   ├── bundles
│   ├── esm2015
│   ├── esm5
│   ├── index.d.ts
│   ├── nx-packaged-two-lib.d.ts
│   ├── nx-packaged-two-lib.metadata.json
│   ├── package.json
│   └── src
└── two-lib.tgz
```

**Comment by affilnost** [comment]
+1

**Comment by Polyterative** [comment]
Still having this issue with Angular 6. Thanks to this I have no way to even create a simple common logger service

**Comment by applexusthirumalai** [comment]
> I get the same error when using sencondary entry points.
> 
> I try to build the library according to the following scheme:
> 
> * All services which have to have one and only one instance per application should be implemented in the BarModule here.
> * And ViewModules should import services from FooModule.
> 
> Here is a link to the git project of the sample library:
> https://github.com/annalen/example-library.
> 
> This example project is structured as follows:
> 
> ```
> example-library
> ├── foo
> |   ├── bar
> |   |	├── src
> |   |	|   ├── bar.module.ts
> |   |	|   └── settings.service.ts
> |   |	├── index.ts
> |   |	├── package.json
> |   |	└── public_api.ts
> |   ├── view
> |   |	├── src
> |   |	|   ├── view.component.ts
> |   |	|   ├── view.component.html
> |   |	|   └── view.module.ts
> |   |	├── index.ts
> |   |	├── package.json
> |   |	└── public_api.ts
> |   └── package.json
> ├── public_api.ts
> └── package.json
> ```
> In this example case, the ViewModule imports the BarModule and the ViewComponent uses the SettingsService.
> 
> And I think that's why I get the following error.:
> 
> ```
> File '.../example-library/lib/foo/bar/src/bar.module.ts' is not under 'rootDir' 
> '...\example-library\lib\foo\view'. 'rootDir' is expected to contain all source files.
> error TS6059: 
> File '.../example-library/lib/foo/bar/src/settings.service.ts' is not under 'rootDir' 
> '..\example-library\lib\foo\view'. 'rootDir' is expected to contain all source files.
> ```
> Thank you for your help.

Did you find the solution? I'm facing the same issue.

**Comment by gnomeontherun** [comment]
I'm building two libraries, on that may be standalone (an icons library) and one (a UI component library) that depends on the icons. I use tsconfig paths to manage references between the two libraries. The only solution that works is to build the standalone library, copy it to my main project node_modules directory (or symlink). This is quirky and makes the build more brittle, however there doesn't appear to be any other option.

**Comment by shruthiv21** [comment]
Hello, I am trying to build two libraries, the structure of it as follows:
```
sample-library
|--- lib1
|      |---- src
|      |        |---- lib
|      |        |        |---- .....
|      |        |---- public_api.ts
|      |        |---- test.ts
|      |---- package.json
|      |---- ng-package.prod.json
|      |---- ng-package.json
|      |---- tsconnfig.lib.json
|      |---- tsconfig.spec.json
|      |---- tslint.json
|--- lib2
|      |---- src
|      |        |---- lib
|      |        |        |---- .....
|      |        |---- public_api.ts
|      |        |---- test.ts
|      |---- package.json
|      |---- ng-package.prod.json
|      |---- ng-package.json
|      |---- tsconnfig.lib.json
|      |---- tsconfig.spec.json
|      |---- tslint.json
|--- package.json
|--- tsconfig.json
|--- tslint.json 
```

When I do ng build lib1, I get error as `'rootDir' is expected to contain all source files.`.
Any idea on how to resolve it?

**Comment by benjamincharity** [comment]
@shruthiv21 In the past when I've seen that error it was because I was bundling items outside of the individual package root (not overall project root).

So a likely issue would be if `lib1` is trying to use files that live outside of `sample-library/lib1`.

For instance, if `lib2` is trying to use a resource from `lib1` you'd need to import it into `lib2` as `import {foo } from 'sample-library/lib1'` rather than using a relative import like `import {foo } from './../lib2'`

**Comment by shruthiv21** [comment]
ok @benjamincharity thank you, will look into it again....

**Comment by shruthiv21** [comment]
@benjamincharity thank you, will look into it again and try to resolve it.

**Comment by fjoalland** [comment]
> I'm building two libraries, on that may be standalone (an icons library) and one (a UI component library) that depends on the icons. I use tsconfig paths to manage references between the two libraries. The only solution that works is to build the standalone library, copy it to my main project node_modules directory (or symlink). This is quirky and makes the build more brittle, however there doesn't appear to be any other option.

Symlink work for you ? For me I always have the same error.

`ERROR: : Unexpected value 'CommonUiModule in /home/user/Documents/pacis1/gmop/kernel/common-ui/dist/pacis1/common-ui/pacis1-common-ui.d.ts' imported by the module 'RqpUiModule in /home/user/Documents/pacis1/gmop/components/auxiliary/rqp/rqp-ui/projects/pacis1/rqp-ui/src/lib/rqp-ui.module.ts'. Please add a @NgModule annotation.

`

**Comment by Proantagonist** [comment]
I have found a solution that suits my needs.

Context: The `utils` package used as an example below is meant to be a framework-agnostic tool set that is used across internal applications (vanilla, angular, etc). If the project was written in JS, then any tool in the package could be utilized.

While better solution exists in the form of custom NPM scripts, I am also developing some Angular packages alongside, which is why I'm using Angular CLI to handle the scaffolding and build process. That's why you won't see any true Angular modules being used in the example.

Anyways, it made sense to split tools by feature or function into separate packages that would then be able to be imported separately into consuming applications. The `utils` package evolved into having secondary endpoints with a source structure that resembled:

```
.
├── dist
├── node_modules
├── packages (1)
│  ├── utils (2)
│  │   └── geometry (3)
│  │   │   ├── src
│  │   │   │   ├── lib
│  │   │   │   │   ├── esri
│  │   │   │   │   │   └── centroidFromGeometry.ts
│  │   │   │   │   ├── generic
│  │   │   │   │   │   └── nearestIndex.ts (6)
│  │   │   │   └── public-api.ts
│  │   │   ├── public-api.ts
│  │   │   ├── ng-package.json (7)
│  │   │   └── package.json
│  │   ├── number (4)
│  │   │   ├── src
│  │   │   │   ├── lib
│  │   │   │   │   └── smallestIndex.ts (5)
│  │   │   │   └── public-api.ts
│  │   │   ├── public-api.ts
│  │   │   ├── ng-package.json
│  │   │   └── package.json
│  │   ├── public-api.ts
│  │   ├── ng-package.json
│  │   └── package.json
├── angular.json
├── package.json
├── tsconfig.json
└── tslint.json
```

**(1)** Renamed default "projects" folder generated by Angular CLI. The scope of the project is `@tamu-gisc`.

**(2)** Scoped package entry point. The entry point is `@tamu-gisc/utils`

**(3)** Secondary entry point for the utils package. The entry point is `@tamu-gisc/utils/geometry`

**(4)** Secondary entry point for the utils package. - The entry point is `@tamu-gisc/utils/number`

**(5)** Dependency FOR **(6)**

**(7)** Specifies the entry file for the secondary entry point:


```
{
  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public-api.ts",
    "umdModuleIds": {}
  }
}
```


When `ng build --project=utils` was executed, NgPackagr attempted to build both **(3)** `geometry` and **(4)** `number` packages as secondary entry points for **(2)** `utils`. However, when NgPackagr builds the **(3)** `geometry` secondary entry point, it realizes that **(5)** is not *at* or *in* the same package directory relative to **(3)** `geometry`'s `public-api.ts` entry file specified in **(7)**.

The solution I found was reformatting the project structure to the following:

```
.
├── dist
├── node_modules
├── packages (1)
│  ├── utils (2)
│  │   ├── internal (8)
│  │   │   ├── geometry
│  │   │   │   ├── esri
│  │   │   │   │   └── centroidFromGeometry.ts
│  │   │   │   ├── generic
│  │   │   │   │   └── nearestIndex.ts (6)
│  │   │   ├── number
│  │   │   │   └── smallestIndex.ts (5)
│  │   ├── geometry (3)
│  │   │   ├── ng-package.json (7)
│  │   │   └── package.json
│  │   ├── number (4)
│  │   │   ├── ng-package.json
│  │   │   └── package.json
│  │   ├── public-api.ts
│  │   ├── public-api.geometry.ts (9)
│  │   ├── public-api.number.ts
│  │   ├── ng-package.json
│  │   └── package.json
├── angular.json
├── package.json
├── tsconfig.json
└── tslint.json
```
 
 With this layout, all the business logic of the library modules goes into **(8)** `internal`, and **(6)** has no problem importing **(5)**. The secondary entry point file for the **(3)** `geometry` package has moved to the root of the **(9)** `utils` package. 

 The `geometry` package **(7)** `ng-package.json` now looks like:

 ```
 {
  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "../public-api.geometry.ts",
    "umdModuleIds": {}
  }
}
```

### Why this works?

This explanation is potentially wrong, so take it with a grain of salt. However, it's the best I can do in my own words.

NgPackagr recognizes secondary entry points by the presence of either `package.json` with the "ngPackage" property OR `ng-package.json` ([Source](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md)). Because of this, it is possible to designate secondary entry points with either or both `package.json` or `ng-package.json` (see **(3)** and **(4)** in the file tree above) and omitting any source files there. The source files are moved to a "shared" space where all packages can access and reference (See **(8)**). The entry file for each of the packages are alongside the primary entry point's entry file (See **(9)**) and in this way the all source files are *at* or *in* the same package directory relative to their respective entry file, meeting the `'rootDir' is expected to contain all source files.` requirement.

**Comment by fjoalland** [comment]
Here is my solution: https://github.com/angular/angular/issues/31989#issuecomment-523396480

I just use yarn instead of npm.

**Comment by maxim1006** [comment]
> I have found a solution that suits my needs.
> 
> Context: The `utils` package used as an example below is meant to be a framework-agnostic tool set that is used across internal applications (vanilla, angular, etc). If the project was written in JS, then any tool in the package could be utilized.
> 
> While better solution exists in the form of custom NPM scripts, I am also developing some Angular packages alongside, which is why I'm using Angular CLI to handle the scaffolding and build process. That's why you won't see any true Angular modules being used in the example.
> 
> Anyways, it made sense to split tools by feature or function into separate packages that would then be able to be imported separately into consuming applications. The `utils` package evolved into having secondary endpoints with a source structure that resembled:
> 
> ```
> .
> ├── dist
> ├── node_modules
> ├── packages (1)
> │  ├── utils (2)
> │  │   └── geometry (3)
> │  │   │   ├── src
> │  │   │   │   ├── lib
> │  │   │   │   │   ├── esri
> │  │   │   │   │   │   └── centroidFromGeometry.ts
> │  │   │   │   │   ├── generic
> │  │   │   │   │   │   └── nearestIndex.ts (6)
> │  │   │   │   └── public-api.ts
> │  │   │   ├── public-api.ts
> │  │   │   ├── ng-package.json (7)
> │  │   │   └── package.json
> │  │   ├── number (4)
> │  │   │   ├── src
> │  │   │   │   ├── lib
> │  │   │   │   │   └── smallestIndex.ts (5)
> │  │   │   │   └── public-api.ts
> │  │   │   ├── public-api.ts
> │  │   │   ├── ng-package.json
> │  │   │   └── package.json
> │  │   ├── public-api.ts
> │  │   ├── ng-package.json
> │  │   └── package.json
> ├── angular.json
> ├── package.json
> ├── tsconfig.json
> └── tslint.json
> ```
> 
> **(1)** Renamed default "projects" folder generated by Angular CLI. The scope of the project is `@tamu-gisc`.
> 
> **(2)** Scoped package entry point. The entry point is `@tamu-gisc/utils`
> 
> **(3)** Secondary entry point for the utils package. The entry point is `@tamu-gisc/utils/geometry`
> 
> **(4)** Secondary entry point for the utils package. - The entry point is `@tamu-gisc/utils/number`
> 
> **(5)** Dependency FOR **(6)**
> 
> **(7)** Specifies the entry file for the secondary entry point:
> 
> ```
> {
>   "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
>   "lib": {
>     "entryFile": "public-api.ts",
>     "umdModuleIds": {}
>   }
> }
> ```
> 
> When `ng build --project=utils` was executed, NgPackagr attempted to build both **(3)** `geometry` and **(4)** `number` packages as secondary entry points for **(2)** `utils`. However, when NgPackagr builds the **(3)** `geometry` secondary entry point, it realizes that **(5)** is not _at_ or _in_ the same package directory relative to **(3)** `geometry`'s `public-api.ts` entry file specified in **(7)**.
> 
> The solution I found was reformatting the project structure to the following:
> 
> ```
> .
> ├── dist
> ├── node_modules
> ├── packages (1)
> │  ├── utils (2)
> │  │   ├── internal (8)
> │  │   │   ├── geometry
> │  │   │   │   ├── esri
> │  │   │   │   │   └── centroidFromGeometry.ts
> │  │   │   │   ├── generic
> │  │   │   │   │   └── nearestIndex.ts (6)
> │  │   │   ├── number
> │  │   │   │   └── smallestIndex.ts (5)
> │  │   ├── geometry (3)
> │  │   │   ├── ng-package.json (7)
> │  │   │   └── package.json
> │  │   ├── number (4)
> │  │   │   ├── ng-package.json
> │  │   │   └── package.json
> │  │   ├── public-api.ts
> │  │   ├── public-api.geometry.ts (9)
> │  │   ├── public-api.number.ts
> │  │   ├── ng-package.json
> │  │   └── package.json
> ├── angular.json
> ├── package.json
> ├── tsconfig.json
> └── tslint.json
> ```
> 
> With this layout, all the business logic of the library modules goes into **(8)** `internal`, and **(6)** has no problem importing **(5)**. The secondary entry point file for the **(3)** `geometry` package has moved to the root of the **(9)** `utils` package.
> 
> The `geometry` package **(7)** `ng-package.json` now looks like:
> 
> ```
> {
>  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
>  "lib": {
>    "entryFile": "../public-api.geometry.ts",
>    "umdModuleIds": {}
>  }
> }
> ```
> 
> ### Why this works?
> This explanation is potentially wrong, so take it with a grain of salt. However, it's the best I can do in my own words.
> 
> NgPackagr recognizes secondary entry points by the presence of either `package.json` with the "ngPackage" property OR `ng-package.json` ([Source](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md)). Because of this, it is possible to designate secondary entry points with either or both `package.json` or `ng-package.json` (see **(3)** and **(4)** in the file tree above) and omitting any source files there. The source files are moved to a "shared" space where all packages can access and reference (See **(8)**). The entry file for each of the packages are alongside the primary entry point's entry file (See **(9)**) and in this way the all source files are _at_ or _in_ the same package directory relative to their respective entry file, meeting the `'rootDir' is expected to contain all source files.` requirement.

This is the only way that helped. Thanks a lot!!!

**Comment by hiepxanh** [comment]
@Proantagonist that worked with me, thank you so much bro

**Comment by benwinding** [comment]
@Proantagonist,

Thanks for the detailed explanation. I guess this implies that the directory structure needs to reflect the dependency graph... if only the documentation had examples like yours!!

**Comment by artemnih** [comment]
In case someone has this issue. There is no need to move files around. Check out how primeng implemented it https://github.com/primefaces/primeng/tree/master/src/app/components
